# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'NearBY' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

   pod 'JSQMessagesViewController', '7.3.4'
  pod 'Alamofire', '4.2.0'
  pod 'GooglePlaces', '2.1.1'
  pod 'BMSAnalytics'
  pod 'BMSPush'
  pod 'OpenWhisk', :git => 'https://github.com/openwhisk/openwhisk-client-swift.git', :tag => '0.2.2'
end
